version: 2

sources:
  - name: dbsales_fbv3
    schema: public
    tables:

      - name: commodities
        description: "Tabela que contem dados historicos de commodities"
        columns:
          - name: Date
            description: "Data da observação"
          - name: Close
            description: "Preço de fechamento da commodity"
          - name: simbolo
            description: "Simbolo da commodity"